analysis_period:
  end_date: '2026-02-28'
  start_date: '2026-02-01'
execution_mode: all
file_config:
  input_file: "D:/OrderDataHandle/\u9633\u5149\u4F18\u91C7\u4EA4\u6613\u8BA2\u5355\
    2\u6708.xlsx"
  output_file: "D:\\OrderDataHandle\\result\\\u6570\u636E\u6E05\u6D17\u6C47\u603B\u7ED3\
    \u679C.xlsx"
report_settings:
  report_mode: "\u65F6\u95F4\u7EF4\u5EA6"
  use_period_data: N
theme: Dark
